### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by veronewra** [Hidden-Identity-Games/blood-on-the-clocktower#119]
Someone (I'm willing to do it too) should create a github workflow for tests that need to pass before merging to main. Also @vermentor check your facebook messenger, I sent you information for a referral!

**Comment by vermentor** [comment]
Good idea.  This project's getting big and complex enough now that tests are starting to become necessary.  The wild west days might be coming to an end ;(
And thanks for the referral!

**Comment by Alphy11** [comment]
First, we need to make tests :-). Currently we just build before merging.  If you want to start writing tests, we should start with some basic playwright tests that make sure we don't break core flows.

**Comment by veronewra** [comment]
I'm having trouble with getting typescript to work for me. Do yall want to cowork tomorrow? @Alphy11 @vermentor

**Comment by veronewra** [comment]
Also, everyone cool with using Jest for testing?
https://www.testim.io/blog/jest-testing-a-helpful-introductory-tutorial/

**Comment by figmatom** [comment]
Jest is meh.  Vitest is the new cool test runner, and I've liked it a lot better than jest as it allows you to use the same exact build system as-is.  
Also would not recommend writing unit tests, as our code isn't stable enough for that to be useful, instead playwright will be more useful to end-to-end test some core scenarios to make sure we didn't break shit.
